global:
  controlPlaneSecurityEnabled: true
  mtls:
    enabled: true
  disablePolicyChecks: false
kiali:
  enabled: true
tracing:
  enabled: true
grafana:
  enabled: true
servicegraph:
  enabled: true
